variable "project_name" {}
variable "environment" {}
variable "private_data_subnet_az1_cidr" {}
variable "private_data_subnet_az2_cidr" {}
variable "database_snapshot_identifier" {}
variable "database_instance_class" {}
variable "availability_zone_1" {}
variable "database_instance_identifier" {}
variable "multi_az_deployment" {}
variable "database_security_group_id" {}